eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
  context-path: /flowapp
spring:
  application:
    name: flowapp
#  zipkin:
#    base-url: http://localhost:9411