eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
  context-path: /flowapp
spring:
  application:
    name: flowapp
  redis:
    host: localhost
    password: 
    port: 6379
    database: 0
    timeout: 0
  session:
    store-type: redis
#  zipkin:
#    base-url: http://localhost:9411
ribbon:  
  ReadTimeout: 6000
  ConnectTimeout: 6000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000